  - name: "tickscripts"
    template:
      src: "TemplatedNoGroupBy.j2"
      dest: "/a/{{item.0.dispositivo}}-{{item.1.instancia}}.yaml"
    with_subelements:
     - "{{ kapacitor_scripts }}"
     - alarmas
